server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      client-id: internal
      client-secret: internal
      authorized-grant-types: password, client_credentials
      scope: openid

spring:
  application:
    name: user
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password:
